/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_co_therhys_Request_Net_MacNet */

#ifndef _Included_uk_co_therhys_Request_Net_MacNet
#define _Included_uk_co_therhys_Request_Net_MacNet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_co_therhys_Request_Net_MacNet
 * Method:    get
 * Signature: (Ljava/lang/String;[[Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_uk_co_therhys_Request_Net_MacNet_get
  (JNIEnv *, jobject, jstring, jobjectArray);

/*
 * Class:     uk_co_therhys_Request_Net_MacNet
 * Method:    post_auth
 * Signature: (Ljava/lang/String;Ljava/lang/String;[[Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_uk_co_therhys_Request_Net_MacNet_post_1auth
  (JNIEnv *, jobject, jstring, jstring, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
